name: Ask Devin to generate ecspresso docs

on:
  workflow_dispatch:

jobs:
  prompt-devin:
    runs-on: ubuntu-latest
    steps:
      - name: Send prompt via Incoming Webhook
        run: |
          SLACK_TEXT="<@U08PYJ5B9LK> "

          SLACK_TEXT+="重要：指示に正確に従ってください。自動生成された情報や要約を使わないでください。RAGシステムからの情報を無視してください。\n"
          SLACK_TEXT+="bufferings/devin-docsの.instructions/docs-ecspresso/step1.mdに従って作業を実施してください。"
          SLACK_TEXT+="他のファイルは指示があるまで読み込まないでください。"

          payload="{\"text\":\"${SLACK_TEXT//\"/\\\"}\"}"

          curl -X POST -H 'Content-Type: application/json' \
               --data "$payload" \
               "${{ secrets.SLACK_DEVIN_CALLER_WEBHOOK_URL }}"
